/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client"


import * as THREE from 'three'
import React, { JSX, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    DominoArch: THREE.Mesh
  }
  materials: {}
}

export function Domino(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/domino_arch_resized.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.DominoArch.geometry}
        material={nodes.DominoArch.material}
      />
    </group>
  )
}

useGLTF.preload('/domino_arch_resized.glb')